apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-mongo-configmap
  namespace: {{ .Release.Namespace }}
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"