apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-mongo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-mongo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: {{ .Values.projectName }}-mongo-configmap

